sogno-platform/dpsim

.gitlab-ci.yml, CMakeLists.txt, Include/dpsim/Config.h.in, Include/dpsim/MNASolverFactory.h, Include/dpsim/MNASolverGpuMagma.h, Packaging/Docker/Dockerfile.dev-centos, Source/CMakeLists.txt, Source/MNASolverEigenSparse.cpp, Source/MNASolverGpuMagma.cpp, Source/MNASolverGpuSparse.cpp, Source/Utils.cpp, cmake/FindMAGMA.cmake
This PR addresses the non-working CUDASparse solver. It also adds a new sparse CUDA-based solver: MNASolverGPUMagma, based on the [magma library](https://icl.cs.utk.edu/magma/).
1. MNASolverGpuSparse did not compile because of a change in MNASolver (making the system matrix a vector of matrices).
- This PR fixes MNASolverGPUSparse so it will compile again
2. MNASolverGpuSparse produces wrong results if there are zeroes on the main diagonal of the system matrix.
- This PR adds MNASolverGPUMagma based on the better documented magma library instead of using CUDASparse and CUDASolver directly.
- The algorithm used by MNASolverGpuMagma is based on an incomplete LU factorization (ILU), similarly to MNASolverGpuSparse. This algorithm requires non-zeroes on the main diagonal of the system matrix. …
=> Fix sparse gpu

Examples/Python/Shmem/test_shmem_import_export.py, models/Source/SP/SP_Ph1_Load.cpp
The villas import didn't work for powerflow simulations with PQ loads due to two reasons:
The SP load didn't use the P and Q attributes internally so that it didn't matter if they pointed to the attributes used by the villas import.
The villas import tasks was dropped by the scheduler since the task system is not fully developed for the PF solver yet.
Both issues have been fixed in this PR.
=> Villas import

Examples/Cxx/CIM/DP_CIGRE_MV_withDG.cpp, Examples/Cxx/CIM/DP_CIGRE_MV_withDG_withLoadStep.cpp, Examples/Cxx/CIM/EMT_CIGRE_MV_withDG.cpp, Examples/Cxx/CIM/EMT_CIGRE_MV_withDG_withLoadStep.cpp, Examples/Cxx/CIM/PF_CIGRE_MV_withDG.cpp, Examples/Cxx/Circuits/DP_Slack_PiLine_PQLoad_with_PF_Init.cpp, Examples/Cxx/Circuits/DP_Slack_PiLine_VSI_Ramp_with_PF_Init.cpp, Examples/Cxx/Circuits/DP_Slack_PiLine_VSI_with_PF_Init.cpp, Examples/Cxx/Circuits/DP_SynGenTrStab_3Bus_Fault.cpp, Examples/Cxx/Circuits/DP_SynGenTrStab_3Bus_SteadyState.cpp, Examples/Cxx/Circuits/DP_SynGenTrStab_SMIB_Fault.cpp, Examples/Cxx/Circuits/DP_SynGenTrStab_SMIB_SteadyState.cpp, Examples/Cxx/Circuits/EMT_DP_SP_Slack_PiLine_PQLoad_FM.cpp, Examples/Cxx/Circuits/EMT_Slack_PiLine_PQLoad_with_PF_Init.cpp, Examples/Cxx/Circuits/EMT_Slack_PiLine_VSI_Ramp_with_PF_Init.cpp, Examples/Cxx/Circuits/EMT_Slack_PiLine_VSI_with_PF_Init.cpp, Examples/Cxx/Circuits/EMT_SynGenDQ7odTrapez_DP_SynGenTrStab_SMIB_Fault.cpp, Examples/Cxx/Circuits/EMT_SynGenDQ7odTrapez_OperationalParams_SMIB_Fault.cpp, Examples/Cxx/Circuits/EMT_SynGenDQ7odTrapez_OperationalParams_SMIB_Fault_JsonSyngenParams.cpp, Examples/Cxx/Circuits/EMT_SynGenDQ7odTrapez_SMIB_Fault.cpp, Examples/Cxx/Circuits/SP_Slack_PiLine_VSI_with_PF_Init.cpp, Examples/Cxx/Circuits/SP_SynGenTrStab_3Bus_Fault.cpp, Examples/Cxx/Circuits/SP_SynGenTrStab_3Bus_SteadyState.cpp, Examples/Cxx/Circuits/SP_SynGenTrStab_SMIB_Fault.cpp, Examples/Cxx/Circuits/SP_SynGenTrStab_SMIB_Fault_KundurExample1.cpp, Examples/Cxx/Circuits/SP_SynGenTrStab_SMIB_SteadyState.cpp, Examples/Cxx/Examples.h
Refactoring of SMIB and 3Bus transient stability examples by moving the scenario's global parameters to examples.h. For future work, scenario parameters (which are not imported) should be defined in examples.h for a better overview.
=> Examples refactoring rebase

.github/workflows/build_test.yaml, .github/workflows/container.yaml, .github/workflows/generate.yaml, docs/sphinx/CMakeLists.txt, public/index.html
This deploys the reference docs to gh-pages and disables the container workflow for all branches but deploy-docker.
=> actions: docs gh-pages deployment

docs/sphinx/Reference.rst
Also include submodules in the automatically generated sphinx documentation.
=> run autodoc on python submodules

docs/sphinx/Reference.rst
This adds a section in the documentation for each dpsimpy submodule.
=> sphinx: add sections in reference

Examples/Python/Villas/docker-compose-dpsim-mqtt/docker-compose.yml, Examples/Python/Villas/docker-compose-dpsim-mqtt/mosquitto.conf, Packaging/Docker/Dockerfile.dev, Packaging/Shell/install-fedora-deps-dev.sh, Packaging/Shell/install-fedora-deps.sh, Packaging/Shell/install-ubuntu-deps.sh
This PR updates the install-shell-scripts to match the recently updated Dockerfiles for Fedora 34. It also adds a docker-compose file for simultaneously starting a dpsim and a mqtt container in the same network. This is especially useful for running the examples in Examples/Python/Villas which use the new InterfaceVillas to communicate with the MQTT broker.
=> Update Dockerfile and shell scripts and provide example compose setup

models/Source/EMT/EMT_Ph1_VoltageSource.cpp
This PR fixes a formatting string for log messages in the EMT Ph1 VoltageSource. Previously, this log call would throw an error because a float is expected for the first format parameter, but an integer is given.
=> fix spdlog formatting string

Packaging/Docker/Dockerfile.dev, Packaging/Docker/Dockerfile.dev-debian, cmake/GetVillasDPsim.cmake
This PR updates the version of VILLASnode used in the Docker installations to match the [changes to dpsim-villas](https://github.com/sogno-platform/dpsim-villas/pull/6). To provide security for future updates, the version of dpsim-villas that is downloaded in GetVillasDPsim.cmake should be fixed to the new merge commit.
=> use new villas version

Packaging/Docker/Dockerfile.dev-centos, requirements.txt
Add additional dependencies to the CentOS Dockerfile to correctly build the Python pillow library.
=> add pillow dependencies to centos dockerfile

Examples/Cxx/CMakeLists.txt, Examples/Cxx/Circuits/EMT_SynGenVBR_OperationalParams_SMIB_Fault.cpp, Examples/Cxx/Circuits/EMT_SynGenVBR_SMIB_Fault.cpp, Examples/Cxx/Components/EMT_SynchronGenerator9OrderDCIM_LoadStep_TurbineGovernor_Exciter.cpp, Examples/Cxx/Components/EMT_SynchronGenerator9OrderVBR_LoadStep_TurbineGovernor_Exciter.cpp, Examples/Cxx/Examples.h, Examples/Cxx/signals/Exciter.cpp, Examples/Notebooks/Components/Syngen_9Order_DCIM_VBR_Governor_Exciter.ipynb, models/Include/cps/Base/Base_SynchronGenerator.h, models/Include/cps/EMT/EMT_Ph3_SynchronGeneratorVBR.h, models/Include/cps/Signal/Exciter.h, models/Include/cps/Signal/TurbineGovernor.h, models/Source/Base/Base_SynchronGenerator.cpp, models/Source/EMT/EMT_Ph3_SynchronGeneratorDQTrapez.cpp, models/Source/EMT/EMT_Ph3_SynchronGeneratorVBR.cpp, models/Source/Signal/Exciter.cpp, models/Source/Signal/TurbineGovernor.cpp
Fixes the former implementations of excitation system (IEEE DC1A) and turbine governor (mechanical-hydraulic control). So far, the two control systems are supported by the 9th order synchronous generator models (DCIM and VBR implementation). They are tested within an additional notebook.
=> Sg controllers

Examples/Cxx/CIM/WSCC_9bus_mult_coupled.cpp, Examples/Cxx/CIM/WSCC_9bus_mult_decoupled.cpp, Examples/Cxx/CIM/WSCC_9bus_mult_diakoptics.cpp, Examples/Cxx/Circuits/DP_Slack_PiLine_VSI_Ramp_with_PF_Init.cpp, Examples/Cxx/Circuits/DP_Slack_PiLine_VSI_with_PF_Init.cpp, Examples/Cxx/Circuits/DP_SynGenTrStab_3Bus_Fault.cpp, Examples/Cxx/Circuits/DP_SynGenTrStab_3Bus_SteadyState.cpp, Examples/Cxx/Circuits/DP_SynGenTrStab_SMIB_Fault.cpp, Examples/Cxx/Circuits/DP_SynGenTrStab_SMIB_SteadyState.cpp, Examples/Cxx/Circuits/EMT_Slack_PiLine_VSI_Ramp_with_PF_Init.cpp, Examples/Cxx/Circuits/EMT_Slack_PiLine_VSI_with_PF_Init.cpp, Examples/Cxx/Circuits/EMT_SynGenDQ7odTrapez_OperationalParams_SMIB_Fault.cpp, Examples/Cxx/Circuits/SP_Slack_PiLine_VSI_with_PF_Init.cpp, Examples/Cxx/Circuits/SP_SynGenTrStab_3Bus_Fault.cpp, Examples/Cxx/Circuits/SP_SynGenTrStab_3Bus_SteadyState.cpp, Examples/Cxx/Circuits/SP_SynGenTrStab_SMIB_Fault.cpp, Examples/Cxx/Circuits/SP_SynGenTrStab_SMIB_Fault_KundurExample1.cpp, Examples/Cxx/Circuits/SP_SynGenTrStab_SMIB_SteadyState.cpp, Examples/Cxx/Components/DP_Inverter_Grid_Parallel_FreqSplit.cpp, Examples/Cxx/Components/DP_Inverter_Grid_Sequential_FreqSplit.cpp, Examples/Cxx/Components/DP_Multimachine_DQ_Parallel.cpp, Examples/Cxx/Components/EMT_SynchronGenerator9OrderDCIM_LoadStep_TurbineGovernor_Exciter.cpp, Examples/Cxx/Components/EMT_SynchronGenerator9OrderVBR_LoadStep_TurbineGovernor_Exciter.cpp, Include/dpsim/Utils.h, Source/Utils.cpp
Refactor `options` of `CommandLineArgs`. There is now a single `options` map, which stores the provided `options` as `string`. Type-specific access to these `options` is enabled by additional methods `getOptionInt`, `getOptionReal`, `getOptionBool` and `getOptionString`. 
Closes #77
=> Refactor cli options

.devcontainer/devcontainer.json, Packaging/Docker/Dockerfile.dev
A devcontainer allows new developers, foreign to the project, to easily
setup a working environment with the needed dependencies to start
developing. The devcontainer is based on `Dockerfile.dev`.
See: https://code.visualstudio.com/docs/remote/containers
This adds a new build stage to `Dockerfile.dev` which adds a non root
user. Devcontainers without a non root user suffer from permission
problems on Linux hosts. This buildstage does not affect existing users
of the `Dockerfile.dev` at all.
See https://code.visualstudio.com/remote/advancedcontainers/add-nonroot-user
Signed-off-by: Philipp Jungkamp <philipp.jungkamp@rwth-aachen.de>
=> Add a basic VS Code devcontainer configuration

Examples/Python/Villas/dpsim-mqtt-cigre-mv-pf-profiles.py
This example is based on the `Shmem/test_shmem_cigre_mv_pf_profiles.py`
and uses the reworked `dpsimpy` / `dpsimpyvillas` interface to communicate
via MQTT.
=> Add new working mqtt example

.github/workflows/build_test_linux_fedora.yaml, .github/workflows/run_villas_example.yaml, examples/villas/docker-compose-tests/docker-compose.yml, examples/villas/docker-compose-tests/mosquitto.conf, examples/villas/dpsim-file.py, examples/villas/dpsim-mqtt-cigre-mv-pf-profiles.py
This PR introduces a new stage in the Github Actions pipeline for testing the python examples which use the `InterfaceVillas` to import or export data. To test these examples, commands have to be run in multiple containers simultaneously. This is implemented in the reusable `run_villas_example` workflow which takes a docker-compose configuration and a list of `docker exec` commands which are then executed across the whole compose setup. For an example, take a look at `test-villas-examples` jobs in the Fedora Workflow file.
=> Test Villas examples in Github pipeline

.github/workflows/build_test_linux_fedora.yaml, dpsim-models/include/dpsim-models/Attribute.h, dpsim-models/include/dpsim-models/DP/DP_Ph1_VoltageSource.h, dpsim-models/include/dpsim-models/Signal/SineWaveGenerator.h, dpsim-models/src/DP/DP_Ph1_NetworkInjection.cpp, dpsim-models/src/DP/DP_Ph1_SynchronGeneratorIdeal.cpp, dpsim-models/src/DP/DP_Ph1_SynchronGeneratorTrStab.cpp, dpsim-models/src/DP/DP_Ph1_VoltageSource.cpp, dpsim-models/src/EMT/EMT_Ph3_AvVoltSourceInverterStateSpace.cpp, dpsim-models/src/EMT/EMT_Ph3_VoltageSourceNorton.cpp, dpsim-models/src/SP/SP_Ph1_AvVoltageSourceInverterDQ.cpp, dpsim-models/src/SP/SP_Ph1_NetworkInjection.cpp, dpsim-models/src/SP/SP_Ph1_SynchronGeneratorTrStab.cpp, dpsim-models/src/SP/SP_Ph1_VoltageSource.cpp, dpsim-models/src/Signal/SignalGenerator.cpp, dpsim-models/src/Signal/SineWaveGenerator.cpp, examples/villas/dpsim-mqtt-producer.py, examples/villas/dpsim-mqtt.py, requirements.txt
This PR fixes multiple bugs regarding the import of the `mVoltageRef` attribute of the `DP_Ph1_VoltageSource`. For this, the reference relationship with voltageRef attributes in components that include voltage sources is reversed. Additionally, the update function for multiple chained dynamic referencing attributes is fixed to allow proper updating of the data pointers.
=> Fix attribute relationships for reference voltages

dpsim-models/src/DP/DP_Ph1_RXLoad.cpp
Fix the copy paste error in rxload mentioned in #118 
Probably, this has not been noticed so far because we usually use a combination of resistor and inductor rather than the capacitor.
=> fix rxload initialization

.github/workflows/container.yaml, .github/workflows/publish_to_pypi.yaml, CMakeLists.txt, dpsim/include/dpsim/Config.h.in, packaging/Docker/Dockerfile.manylinux, pyproject.toml, requirements-manylinux.txt
Adds a new workflow for packaging the dpsim source distribution as well as building multiple binary wheels for Python versions 3.6 to 3.11 using [cibuildwheel](https://github.com/pypa/cibuildwheel). Every commit to the master branch will be pushed to TestPyPi while only tagged commits will also be uploaded to production PyPi.
Closes #127
=> Add Github actions workflow for publishing to PyPi

.github/workflows/publish_to_pypi.yaml, packaging/Docker/Dockerfile.manylinux
Installs and forces the use of GCC Version 11 in the ManyLinux Docker image.
This is a short-term solution for #145 
It is a follow-up of #139, which added a new workflow for packaging the dpsim source distribution as well as building multiple binary wheels for Python versions 3.6 to 3.11 using [cibuildwheel](https://github.com/pypa/cibuildwheel). Every commit to the master branch will be pushed to TestPyPi while only tagged commits will also be uploaded to production PyPi.
=> Force gcc 11 in manylinux docker image

.gitlab-ci.yml
to make docker happy we have to specify the context directory. The other dockerfiles probably need this patch as well.
This fixes the gitlab CI.
Signed-off-by: Niklas Eiling <niklas.eiling@eonerc.rwth-aachen.de>
=> fix gitlab ci using old docker syntax

.github/workflows/container.yaml, CMakeLists.txt, packaging/Docker/Dockerfile.manylinux, pyproject.toml, setup.cfg
Attempts to fix the wheel building and uploading process for the publish_to_pypi workflow. Now correctly enforces the use of the GCC 11 compiler in Python builds (see #145) and employs the CMake FindPython3 function which somehow works better than the previously used FindPython function. Also updates the Python Version number to 1.1.0 which allows for an actual upload to PyPi (Version 1.0.0 is already present there).
=> Fix PyPi-Upload CI workflow

.github/workflows/publish_to_pypi.yaml
Triggers the publish_to_pypi workflow for every push to a tag. This means that every time a new tag is created, the workflow will attempt to build the code associated with this tag and push the finished package to TestPyPi and PyPi. Because tags and branches are independent, the workflow will not check whether the tagged commit also exists on the master branch.
=> Trigger PyPi-Workflow for tags

.github/workflows/container.yaml
Enables the build and upload of the RockyLinux Docker image via the container workflow. After the workflow is triggered once and the RockyLinux image is uploaded to Docker Hub, the build_test_linux_rocky CI workflow should be able to run successfully.
=> Build and push RockyLinux image

dpsim-models/include/dpsim-models/DP/DP_Ph1_PQLoadCS.h, dpsim-models/include/dpsim-models/DP/DP_Ph1_RxLine.h, dpsim-models/include/dpsim-models/DP/DP_Ph1_SynchronGeneratorTrStab.h, dpsim-models/include/dpsim-models/DP/DP_Ph1_VoltageSourceRamp.h, dpsim-models/include/dpsim-models/EMT/EMT_Ph1_VoltageSourceRamp.h, dpsim-models/include/dpsim-models/EMT/EMT_Ph3_RXLoad.h, dpsim-models/include/dpsim-models/EMT/EMT_Ph3_RxLine.h, dpsim-models/include/dpsim-models/EMT/EMT_Ph3_SynchronGeneratorTrStab.h, dpsim-models/include/dpsim-models/SP/SP_Ph1_Load.h, dpsim-models/include/dpsim-models/SP/SP_Ph1_RXLine.h, dpsim-models/include/dpsim-models/SP/SP_Ph1_SynchronGeneratorTrStab.h, dpsim-models/src/DP/DP_Ph1_PQLoadCS.cpp, dpsim-models/src/DP/DP_Ph1_PiLine.cpp, dpsim-models/src/DP/DP_Ph1_RXLoad.cpp, dpsim-models/src/DP/DP_Ph1_RXLoadSwitch.cpp, dpsim-models/src/DP/DP_Ph1_RxLine.cpp, dpsim-models/src/DP/DP_Ph1_SynchronGeneratorIdeal.cpp, dpsim-models/src/DP/DP_Ph1_SynchronGeneratorTrStab.cpp, dpsim-models/src/DP/DP_Ph1_VoltageSourceRamp.cpp, dpsim-models/src/EMT/EMT_Ph1_VoltageSourceRamp.cpp, dpsim-models/src/EMT/EMT_Ph3_PiLine.cpp, dpsim-models/src/EMT/EMT_Ph3_RXLoad.cpp, dpsim-models/src/EMT/EMT_Ph3_RxLine.cpp, dpsim-models/src/EMT/EMT_Ph3_SynchronGeneratorIdeal.cpp, dpsim-models/src/EMT/EMT_Ph3_SynchronGeneratorTrStab.cpp, dpsim-models/src/SP/SP_Ph1_Load.cpp, dpsim-models/src/SP/SP_Ph1_PiLine.cpp, dpsim-models/src/SP/SP_Ph1_RXLine.cpp, dpsim-models/src/SP/SP_Ph1_SolidStateTransformer.cpp, dpsim-models/src/SP/SP_Ph1_SynchronGeneratorTrStab.cpp
For all components that declare some kind of subcomponents, this PR unifies the handling of these subcomponents such that:
- Subcomponents are always added to `mSubComponents`
- Subcomponent MNA methods (`mnaPreStep`, `mnaPostStep`...) are called directly in the same-named parent method and not through custom tasks
- The parent calls the subcomponent's methods by iterating through `mSubComponents`
Based on #140 
Related to #131
=> Unify subcomponent handling and call MNA methods through the parent

dpsim/src/MNASolverPlugin.cpp
The missing `this`  in logger macros in `MnaSolverPlugin` gave compiler errors with standard cmake configuration and thus is complemented by this PR.
=> Fix missing 'this' in logger macros

CMakeLists.txt, cmake/FetchKLU.cmake, dpsim-models/CMakeLists.txt, dpsim-models/src/CMakeLists.txt, dpsim/examples/cxx/CMakeLists.txt, dpsim/src/CMakeLists.txt, pyproject.toml, setup.cfg, setup.py, sonar-project.properties
Removes the Python versions 3.6 and 3.7 from the PyPi build action. To ensure that the KLU libraries can be found during the wheel build, the FetchKLU cmake action is changed to use `FetchContent_MakeAvailable`. Finally, DPsim's version number is increased to v1.1.1 and a corresponding PyPi package uploaded.
Closes #228
=> Remove Python versions 3.6 and 3.7 for PyPi upload 

.github/workflows/build_test_linux_fedora.yaml, .github/workflows/build_test_linux_fedora_minimal.yaml, .github/workflows/build_test_linux_rocky.yaml, .github/workflows/build_test_windows.yaml
Disables all actions except SonarCloud when opening or updating a PR. Actions are still run on every push, so whenever a new commit is pushed onto the PRs base branch, the results of these actions will also show up in the PR.
=> Disable test actions for PRs

dpsim-models/include/dpsim-models/DP/DP_Ph1_RXLoad.h, dpsim-models/include/dpsim-models/EMT/EMT_Ph3_RXLoad.h, dpsim-models/include/dpsim-models/SP/SP_Ph1_Load.h, dpsim-models/src/DP/DP_Ph1_RXLoad.cpp, dpsim-models/src/EMT/EMT_Ph3_RXLoad.cpp, dpsim-models/src/SP/SP_Ph1_Load.cpp
This PR fixes the initialization of the interface current of `RXLoad` in EMT. Moreover, the deprecated fuctions `clone` of `SP_Load`, `DP_RXLoad` and `EMT_Load` are deleted.
Closes #240
=> Fix initialization rxload

dpsim/src/pybind/main.cpp
This commit fixes an error when using the dpsim python interface (`dpsimpy`). 
The stop function was not declared in the `pybind/main.cpp` and then not exposed in python. The result was that the program gets an exception and the last data is not written to the output.
A line was added to expose the `stop` function.
=> Fix: add missing stop function in the Simulation using pybind

dpsim/src/pybind/main.cpp
This PR fixes an error when using the dpsim python interface `dpsimpy`. The `stop` function was not declared in the `pybind/main.cpp` and then not exposed in python. Now, a line was added to expose the `stop` function.
Closes #248
=> Hotfix: missing simulation stop

cmake/FetchGridData.cmake, docs/hugo/content/en/docs/Overview/_index.md
This PR removes further dependencies on archived RWTH gitlab repositories by making instead use of the corresponding github repositories.
=> Remove further RWTH gitlab dependencies

.github/workflows/sonar_cloud.yaml
Due to end of support of the Java 11 (LTS) in Sonar, this PR updates the version of Sonar Scanner to 5.0.1.3006. Additionally, the warnings because of Node.js (version 16 to be unsupported in the near future) are corrected. Actions `cache` is also updated to `v4`. The action for `setup-java` was removed (we use now the JRE included in `sonar-scanner`).
This closes #251
=> Fix sonar scanner errors due to Java deprecated version

.github/workflows/publish_to_pypi.yaml
This PR ensures that python is found for the building process for pypi.
Closes #255
=> Change python to python3 to run the building for pypi

CMakeLists.txt
Add definition to silence MSVC error C2220
=> Supress a warning treated as an error in MSVC

docs/doxygen/Doxyfile.in
With the new structure in PR #94, that is:
* dpsim
* dpsim-models
* dpsim-villas each one has a src and include folders. This breaks the INPUT argument in Doxygen.
This commit fixes this and resolves #260.
=> Fixes to the doxygen documentation INPUT line

README.md
Changing the badge without status from CentOS times, to the one pointing to the RockyLinux used in the pipeline.
=> Replace CentOS badge with RockyLinux badge

.editorconfig
At some point the indentation size changed to two, but the editorconfig still  shows four. This fixes that.
We also seem to now use spaces rather than tabs.
=> editorconfig: set C++ indentation size to two

.github/workflows/build_test_linux_fedora.yaml, .github/workflows/build_test_linux_fedora_minimal.yaml, .github/workflows/build_test_linux_rocky.yaml, .github/workflows/build_test_windows.yaml, .github/workflows/container.yaml, .github/workflows/documentation-fein.yaml, .github/workflows/documentation.yaml, .github/workflows/publish_to_pypi.yaml, .github/workflows/run_and_profile_example.yaml, .github/workflows/run_villas_example.yaml
Changelog
===
In general, the versions of the actions were updated for checkout, cache, download and upload artifacts. Aditionally, the parallel build with a static value in an environment variable `-j2` was changed to the `--parallel $(nproc)` argument to the command to pick automatically the value.
In particular, other changes were done:
- `build_test_linux_fedora_minimal.yaml`
- the build cache is updated with a new name to preserve for the same reference (branch, push) and not for the same commit
- `build_test_linux_fedora.yaml`
- setup a build cache for dpsimpy & examples
- archive in a different cache (not overwriting the others) per commit sha
- changes to the archiving of build of cxx examples
- input from the previous stage and recompile and save for the current compilation
- …
=> Update actions in workflow and improve parallelisation and cache handling

.github/workflows/documentation.yaml, .github/workflows/publish_to_pypi.yaml
This fixes the current problems in the workflow:
- The option for `make` to be parallel was `--jobs`
- The version for publishing has now a different release tag, updated
=> Fix workflow: option for parallel in make and error in publish to PyPI

dpsim-models/include/dpsim-models/MNAStampUtils.h, dpsim-models/src/DP/DP_Ph1_Switch.cpp, dpsim-models/src/DP/DP_Ph1_varResSwitch.cpp, dpsim-models/src/DP/DP_Ph3_SeriesSwitch.cpp, dpsim-models/src/EMT/EMT_Ph3_SeriesSwitch.cpp, dpsim-models/src/EMT/EMT_Ph3_Switch.cpp, dpsim-models/src/MNAStampUtils.cpp, dpsim-models/src/SP/SP_Ph1_Switch.cpp, dpsim-models/src/SP/SP_Ph1_varResSwitch.cpp
This PR extends functionality of `MNAStampUtils` with functions to stamp conductance/admittance as scalar matrix and reuses the stamping logic for switches.
- Reuse conductance/admittance stamping logic for all switch components (at least, all that I found😅): `DP_Ph1_Switch`, `DP_Ph1_varResSwitch`, `DP_Ph3_SeriesSwitch`, `EMT_Ph3_SeriesSwitch`, `EMT_Ph3_Switch`, `SP_Ph1_Switch`, `SP_Ph1_varResSwitch.`
- `MNAStampUtils`: Add functions for stamping conductance/admittance value as a scalar matrix. These functions are used for optimized conductance/admittance stamping by components with symmetric phase impedance, such as `DP_Ph3_SeriesSwitch`, `EMT_Ph3_SeriesSwitch`.
- **Issue Reference**: These changes were discussed in an issue: https://github.com/sogno-platform/dpsim/issues/288
- …
=> Reuse conductance stamp code

dpsim-models/include/dpsim-models/MNAStampUtils.h, dpsim-models/src/EMT/EMT_Ph3_ReducedOrderSynchronGeneratorVBR.cpp, dpsim-models/src/EMT/EMT_Ph3_SynchronGeneratorVBR.cpp, dpsim-models/src/MNAStampUtils.cpp
This PR fixes and extends functionality of `MNAStampUtils` and reuses the stamping logic for EMT synchronous generators.
- **MNAStampUtils: Fix stamping of full matrices (i.e., matrices with non-zero off-diagonal elements)** 
The incorrect logic for full matrices in `MNAStampUtils` was not previously recognized because 3-phase components that already used `MNAStampUtils`  (i.e. 3-phase R, L, C components) do not have coupling between the phases (their conductance matrix is diagonal). The incorrect logic became apparent when the code was reused for stamping synchronous generator's conductance matrix. 
- **MNAStampUtils: add matrix stamp functions with optimized logic**
Added functions `stamp3x3ConductanceMatrixBetween2Nodes` and `stamp3x3ConductanceMatrixNodeToGround,` that do not check if …
=> Reuse stamp code for EMT synchron. generators

.github/workflows/build_test_linux_fedora.yaml, .github/workflows/run_villas_example.yaml
In our workflow, docker-compose was used corresponding to v1.
In the current ubuntu:latest the support for v1 has been deprecated.
This PR upgrades the action to v2 and fixes #318
=> Fix the villas examples workflow

dpsim-models/include/dpsim-models/Components.h, dpsim-models/include/dpsim-models/EMT/EMT_Ph3_CurrentSource.h, dpsim-models/include/dpsim-models/EMT/EMT_Ph3_SSN_Capacitor.h, dpsim-models/include/dpsim-models/EMT/EMT_Ph3_SSN_Full_Serial_RLC.h, dpsim-models/include/dpsim-models/EMT/EMT_Ph3_SSN_Inductor.h, dpsim-models/src/CMakeLists.txt, dpsim-models/src/EMT/EMT_Ph3_CurrentSource.cpp, dpsim-models/src/EMT/EMT_Ph3_SSN_Capacitor.cpp, dpsim-models/src/EMT/EMT_Ph3_SSN_Full_Serial_RLC.cpp, dpsim-models/src/EMT/EMT_Ph3_SSN_Inductor.cpp, dpsim/examples/cxx/CMakeLists.txt, dpsim/examples/cxx/Circuits/EMT_Ph3_R3C1L1CS1_RC_vs_SSN.cpp, dpsim/examples/cxx/Circuits/EMT_Ph3_RLC1VS1_RC_vs_SSN.cpp, dpsim/src/pybind/EMTComponents.cpp, examples/Notebooks/Circuits/EMT_Ph3_compare_RC_SSN.ipynb
This branch focusses on the implementation of a State Space Nodal (SSN) simulation approach for real time analysis within the EMT domain limited to linear components. The approach is based on the paper “A Combined State-Space Nodal Method for the Simulation of Power System Transients” ,doi: [10.1109/TPWRD.2010.2090364](https://doi.org/10.1109/TPWRD.2010.2090364) of Dufour et al. .
Linear State Space Nodal models of basic components and linear circuits like an RLC circuit are implemented as single SSN components. To achieve this a state space representation for the electrical element or circuit is derived. Those equations are discretized using the trapezoidal rule of integration. The system of linear equations is manipulated such that current states in the output equations of the state …
=> Linear SSN

.clang-format, dpsim-models/include/dpsim-models/Attribute.h, dpsim-models/include/dpsim-models/DP/DP_Ph1_ProfileVoltageSource.h, dpsim-models/include/dpsim-models/DP/DP_Ph1_VoltageSource.h, dpsim-models/include/dpsim-models/Signal/DCGenerator.h, dpsim-models/src/CMakeLists.txt, dpsim-models/src/DP/DP_Ph1_ProfileVoltageSource.cpp, dpsim-models/src/DP/DP_Ph1_VoltageSource.cpp, dpsim-models/src/Signal/DCGenerator.cpp, dpsim-villas/examples/cxx/FpgaExample.cpp, dpsim-villas/include/dpsim-villas/InterfaceVillas.h, dpsim-villas/include/dpsim-villas/InterfaceVillasQueueless.h, dpsim-villas/include/dpsim-villas/InterfaceWorkerVillas.h, dpsim-villas/src/CMakeLists.txt, dpsim-villas/src/InterfaceVillas.cpp, dpsim-villas/src/InterfaceVillasQueueless.cpp, dpsim-villas/src/InterfaceWorkerVillas.cpp, dpsim/include/dpsim/Interface.h, dpsim/include/dpsim/InterfaceQueued.h, dpsim/include/dpsim/InterfaceWorker.h, dpsim/include/dpsim/Simulation.h, dpsim/src/CMakeLists.txt, dpsim/src/Interface.cpp, dpsim/src/InterfaceQueued.cpp, dpsim/src/KLUAdapter.cpp, dpsim/src/Simulation.cpp, packaging/Docker/Dockerfile.dev, packaging/Docker/Dockerfile.dev-debian, packaging/Docker/Dockerfile.dev-rocky, packaging/Docker/Dockerfile.manylinux
villas interface: improve real-time capability
The original villas interface was not real-time capable because of the queue it uses. This commit creates an interface for villas interfaces, moves the old implementation to InterfaceQueued and adds a new queueless, threadless implementation InterfaceQueueless.
models: Add DC voltage source
The DP_Ph1_VoltageSource always calculates a sinusoidal signal, even if we only want to set a DC value. This commit adds a DC generator for the model so it can be significantly faster if we do not need the sinusoidal signal.
FpgaExample: use new villas interface and make logging optional.
=> New queueless VILLAS interface / improve real-time performance

.github/workflows/build_test_linux_fedora.yaml, .github/workflows/build_test_linux_fedora_minimal.yaml, .github/workflows/build_test_linux_rocky.yaml, .github/workflows/build_test_windows.yaml, .github/workflows/sonar_cloud.yaml, cmake/FetchCIMpp.cmake, packaging/Docker/Dockerfile.dev, packaging/Docker/Dockerfile.dev-debian, packaging/Docker/Dockerfile.dev-rocky, packaging/Docker/Dockerfile.manylinux
- Since we work now mainly from forks, I extended the actions triggered `on: push` to be additionally triggered `on: pull_request`. Activity types set to `types: [opened, synchronize, reopened]`. For more details see [here](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request). An optimised version of this is to additionally prevent feature branches to trigger on push when they already have a PR: `on: [push, pull_request]`
- Pin the version of libcimpp to avoid failure of windows workflow caused by [sogno-platform/libcimpp#29](https://github.com/sogno-platform/libcimpp/pull/29).
=> Trigger actions for PRs and pin the version of libcimpp

packaging/Docker/Dockerfile.dev, packaging/Docker/Dockerfile.dev-debian, packaging/Docker/Dockerfile.dev-rocky, packaging/Docker/Dockerfile.manylinux
This PR fixes the building process of CIMpp in the Docker files. Since we are now checking out a specific commit of this library, we need to make sure that the git submodules are updated after the checkout.
=> Fix submodule initialization for CIMpp in Dockerfiles.

.github/workflows/publish_to_pypi.yaml, pyproject.toml
See: https://github.com/pypa/gh-action-pypi-publish?tab=readme-ov-file#trusted-publishing
Closes #367, #366
=> feat(ci): Use trusted / OIDC publishing to PyPi.org

dpsim/examples/cxx/CMakeLists.txt, dpsim/include/dpsim/Config.h.in, dpsim/include/dpsim/Simulation.h, dpsim/include/dpsim/Utils.h, dpsim/src/Utils.cpp, dpsim/src/pybind/EMTComponents.cpp
We actually depend in a very few places on this library.
Lets make it optional.
Depends on #342 to be merged first.
=> Allow builds without nlohmann/json library

dpsim-models/include/dpsim-models/Base/Base_Ph1_Transformer.h, dpsim-models/include/dpsim-models/SP/SP_Ph1_AvVoltageSourceInverterDQ.h, dpsim-models/include/dpsim-models/SP/SP_Ph1_Load.h, dpsim-models/include/dpsim-models/SP/SP_Ph1_NetworkInjection.h, dpsim-models/include/dpsim-models/SP/SP_Ph1_PiLine.h, dpsim-models/include/dpsim-models/SP/SP_Ph1_RXLine.h, dpsim-models/include/dpsim-models/SP/SP_Ph1_SynchronGenerator.h, dpsim-models/include/dpsim-models/SP/SP_Ph1_Transformer.h, dpsim-models/src/DP/DP_Ph1_Transformer.cpp, dpsim-models/src/SP/SP_Ph1_AvVoltageSourceInverterDQ.cpp, dpsim-models/src/SP/SP_Ph1_Load.cpp, dpsim-models/src/SP/SP_Ph1_NetworkInjection.cpp, dpsim-models/src/SP/SP_Ph1_PiLine.cpp, dpsim-models/src/SP/SP_Ph1_RXLine.cpp, dpsim-models/src/SP/SP_Ph1_SynchronGenerator.cpp, dpsim-models/src/SP/SP_Ph1_Transformer.cpp, dpsim/src/PFSolver.cpp
This PR aims at reducing the number of unnecessarily used attributes, as discussed in #330. The PR does the following:
1. Declares base/nominal voltages of SP components, used in PFSolver, as `private Real` member variables instead of `Attribute<Real>`.
2. Adds getter functions in these components to get base/nominal voltages.
3. Uses getter functions instead of` get() `function of TypedAttribute to get base voltage in PFSolver.
=> Reduce attributes number

.github/workflows/build_nix.yaml, docs/hugo/content/en/docs/Getting started/build.md, flake.lock, flake.nix, packaging/Nix/cimpp.nix, packaging/Nix/dpsim.nix, packaging/Nix/dpsimpy.nix, packaging/Nix/readerwriterqueue.nix, packaging/Nix/shell.nix, packaging/Nix/suitesparse.nix, packaging/Nix/sundials.nix
=> Nix packaging

dpsim-models/src/SystemTopology.cpp, dpsim/include/dpsim/Timer.h, dpsim/src/KLUAdapter.cpp, dpsim/src/Timer.cpp, packaging/Docker/Dockerfile, packaging/Docker/Dockerfile.dev, packaging/Docker/Dockerfile.dev-minimal
This upgrades the versions of Fedora based containers to 42, with the newest villas version.
This gave me a few extra work:
- Catch exception throw in destructor of Timer
- Add logger to Timer
- Fix iterator when deleting components
- Avoid accessing empty vectors in KLUAdapter when checking for path in partial refactorization
This solves #371
=> Upgrade Fedora dockerfiles to v42

.github/workflows/build_test_linux_rocky.yaml, dpsim/include/dpsim/DataLoggerInterface.h, dpsim/include/dpsim/Interface.h, dpsim/src/pybind/Attributes.cpp, packaging/Docker/Dockerfile.dev, packaging/Docker/Dockerfile.dev-rocky
This PR aims to fix:
- Problems compiling with clang using pybind (errors that do not allow the binding to be active)
- Reinstate ability of the workflow to compile using clang with pybind activated
=> pybind: Errors when compiling with clang
